# MID TERM TEST 2023/2024

### Duration: 2 hours

Instructions:
1. You can only refer to lecture notes.
2. Save this file as your _MatricNo-MTT_.
3. File should be saved as _.ipynb_ file.
4. Submission will be done after the test ended. Please upload the file in the designated folder in the e-learning. The access to the e-learning will only be closed 10 minutes after the test ended.

_Please run below code to import Numpy and pandas_

In [ ]:
import numpy as np
import pandas as pd

## QUESTION 1 [15 MARKS]

##### Use only Python basics for this question (NumPy or pandas are not allowed).

Given the quotes by Erin Shellman:

Erin Shellman has quoted two statements which are 'The most interesting types of data are those collected for one purpose and used for another' and 'As a data scientist, even if you do not have the domain expertise, you can learn it and can work on any problem that can be quantitatively described'


### Question 1(a)(i) - 3 marks

Do the string slicing to produce the output of:

'As a data scientist, even if you do not have the domain expertise, you can learn it and can work on any problem that can be quantitatively described' quote by Erin Shellman

In [ ]:
quotes = "Erin Shellman has quoted two statements which are \
'The most interesting types of data are those collected for one purpose and used for another' and \
'As a data scientist, even if you do not have the domain expertise, \
you can learn it and can work on any problem that can be quantitatively described'"

# WRITE YOUR CODE HERE
first_quote_index = quotes.find("\'")
second_quote_index = quotes.find("\'", first_quote_index + 1)
third_quote_index = quotes.find("\'", second_quote_index + 1)

str_slice = quotes[third_quote_index:] + " quote by Erin Shellman"
str_slice

"'As a data scientist, even if you do not have the domain expertise, you can learn it and can work on any problem that can be quantitatively described' quote by Erin Shellman"

### Question 1(a)(ii) - 3 marks

Perform the ``split`` method to split both quotes.
Then print both of them as below:

    Two quotes from Erin Shellman:

    1st Quote: The most interesting types of data are those collected for one purpose and used for another

    2nd Quote: As a data scientist, even if you do not have the domain expertise, you can learn it and can work on any problem that can be quantitatively described

In [ ]:
# WRITE YOUR CODE HERE
first_quote = quotes.split("\'")[1]
second_quote = quotes.split("\'")[3]

print("Two quotes from Erin Shellman:\n")
print("1st Quote: " + first_quote + "\n")
print("2nd Quote: " + second_quote)

Two quotes from Erin Shellman:

1st Quote: The most interesting types of data are those collected for one purpose and used for another

2nd Quote: As a data scientist, even if you do not have the domain expertise, you can learn it and can work on any problem that can be quantitatively described


### Question 1(b) - 3 marks

Write a program to find the numbers between 1500 and 4500 (both included) which are divisible by 9 and multiple of 3. Those numbers need to be stored in an array. Display all the size of the array.

In [ ]:
# WRITE YOUR CODE HERE
numList = [x for x in range(1500, 4501) if (x%9 == 0 and x%3 == 0)]
arr = np.array(numList)
arr

array([1503, 1512, 1521, 1530, 1539, 1548, 1557, 1566, 1575, 1584, 1593,
       1602, 1611, 1620, 1629, 1638, 1647, 1656, 1665, 1674, 1683, 1692,
       1701, 1710, 1719, 1728, 1737, 1746, 1755, 1764, 1773, 1782, 1791,
       1800, 1809, 1818, 1827, 1836, 1845, 1854, 1863, 1872, 1881, 1890,
       1899, 1908, 1917, 1926, 1935, 1944, 1953, 1962, 1971, 1980, 1989,
       1998, 2007, 2016, 2025, 2034, 2043, 2052, 2061, 2070, 2079, 2088,
       2097, 2106, 2115, 2124, 2133, 2142, 2151, 2160, 2169, 2178, 2187,
       2196, 2205, 2214, 2223, 2232, 2241, 2250, 2259, 2268, 2277, 2286,
       2295, 2304, 2313, 2322, 2331, 2340, 2349, 2358, 2367, 2376, 2385,
       2394, 2403, 2412, 2421, 2430, 2439, 2448, 2457, 2466, 2475, 2484,
       2493, 2502, 2511, 2520, 2529, 2538, 2547, 2556, 2565, 2574, 2583,
       2592, 2601, 2610, 2619, 2628, 2637, 2646, 2655, 2664, 2673, 2682,
       2691, 2700, 2709, 2718, 2727, 2736, 2745, 2754, 2763, 2772, 2781,
       2790, 2799, 2808, 2817, 2826, 2835, 2844, 28

### Question 1(c) - 6 marks

Write a function named `Prime` that receive a list of numbers and to return a list of only the prime numbers.<br> A prime number is a whole number greater than 1 whose only can be divided by only 1 and the number itself.<br> Test your function using the test codes given.

In [ ]:
# WRITE YOUR CODE HERE
def Prime(num_list):
    prime_list = []
    for x in num_list:
        if x > 1:
            prime_list.append(x)
            for i in range(2, x):
                if x%i == 0:
                    if x in prime_list:
                        prime_list.remove(x)
    return prime_list

In [ ]:
# Test Code 1

number = [2,3,4,5,6,7]

result = Prime(number)
print(result)

[2, 3, 5, 7]


In [ ]:
# Test Code 2

number = list(range(10, 30))

result = Prime(number)
print(result)

[11, 13, 17, 19, 23, 29]


In [ ]:
# Test Code 3

number = list(range(-3, 11))

result = Prime(number)
print(result)

[2, 3, 5, 7]


## QUESTION 2 [15 MARKS]

For this question, you are using Blood Transfusion Dataset (Blood Transfusion.csv). Here are the description of each column:

    Column 1: Number of months since the particular donor's most recent donation
    Column 2: Total number of donations that the donor has made
    Column 3: Total amound of blood that the donor has donated (cubic centimeters)
    Column 4: Number of months since the donor's first donation
    Column 5: This is a binary variable which represents whether the donor donated blood in March 2007


### Question 2(a) - 2 marks

Load the dataset into variable name ``transfuse``. Display the first 7 rows.

In [ ]:
# WRITE YOUR CODE HERE
transfuse = pd.read_csv("Blood Transfusion.csv")
transfuse.head(7)

Recency (months)  Frequency (times)  Monetary (c.c. blood)  Time (months)   
0                 2                 50                  12500             98  \
1                 0                 13                   3250             28   
2                 1                 16                   4000             35   
3                 2                 20                   5000             45   
4                 1                 24                   6000             77   
5                 4                  4                   1000              4   
6                 2                  7                   1750             14   

   whether he/she donated blood in March 2007  
0                                           1  
1                                           1  
2                                           1  
3                                           1  
4                                           0  
5                                           0  
6                                           1

### Question 2(b) - 1 mark

What is the size of the dataset?

In [ ]:
# WRITE YOUR CODE HERE
transfuse.shape[0]


748

### Question 2(c) - 2 marks

How many donors have donated more than 10,000 cubic centimeters blood?

In [ ]:
# WRITE YOUR CODE HERE
len(transfuse[transfuse['Monetary (c.c. blood)'] > 10000])


5

### Question 2(d) - 2 marks

What is the highest frequency of donation in the dataset and what is the total monetory of the donor?

In [ ]:
# WRITE YOUR CODE HERE
index = transfuse['Frequency (times)'].idxmax()
transfuse[['Frequency (times)', 'Monetary (c.c. blood)']].iloc[index]

Frequency (times)           50
Monetary (c.c. blood)    12500
Name: 0, dtype: int64

### Question 2(e) - 3 marks

How many donors were in March 2007?

In [ ]:
# WRITE YOUR CODE HERE
transfuse['whether he/she donated blood in March 2007'].sum()


178

### Question 2(f) - 2 marks

What is the average number of months did the donors take to do the next donation?

In [ ]:
# WRITE YOUR CODE HERE
diff_no_of_months = transfuse['Time (months)'] - transfuse['Recency (months)']
average_no_of_months = diff_no_of_months / transfuse['Frequency (times)']
average_no_of_months

0       1.920000
1       2.153846
2       2.125000
3       2.150000
4       3.166667
         ...    
743     7.500000
744    15.500000
745    13.000000
746     0.000000
747     0.000000
Length: 748, dtype: float64

### Question 2(g) - 3 marks

How many donors have donated only 2 times? What is the longest time (in months) for the donor took before he or she did his or her second donation?

In [ ]:
# WRITE YOUR CODE HERE
donors_2_times = transfuse[transfuse['Frequency (times)'] == 2]
print("Number of donors that donated only 2 times: " + str(len(donors_2_times)))

diff_time = donors_2_times['Time (months)'] - donors_2_times['Recency (months)']
longest_diff_time = diff_time.max()
print("The longest time (in months) for the donor took before he or she did his or her second donation: " + str(longest_diff_time) + " months")

Number of donors that donated only 2 times: 112
The longest time (in months) for the donor took before he or she did his or her second donation: 64 months


## QUESTION 3 [20 MARKS]

Given a list of results of an event for 10 students for 7 courses where **1 indicates the student passes** for the event, while **0 indicates the student is fails**. The data is given in a simple list described as follows:

<br>
<img src="F1.png", style="width:500px";>

The name list and the course list also given. The order of the course and name in the results data are complement to both variables.


In [ ]:
result = np.array([1,0,0,1,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,1,1,1,1])
name_list = np.array(["S1","S2","S3","S4","S5","S6","S7","S8","S9","S10"])
course_list = np.array(["Course1","Course2","Course3","Course4","Course5","Course6","Course7"])

print(result)
print()
print(name_list)
print()
print(course_list)

[1 0 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 0
 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1]

['S1' 'S2' 'S3' 'S4' 'S5' 'S6' 'S7' 'S8' 'S9' 'S10']

['Course1' 'Course2' 'Course3' 'Course4' 'Course5' 'Course6' 'Course7']


### Question 3(a) - 3 marks

Based on the given data, create a 2D numpy array (named: ``result_arr``) where:
- ROW represents each student
- COLUMN represents each day

The output should be:

<br>
<img src="F2.png", style="width:150px";>

In [ ]:
# WRITE YOUR CODE HERE
result_arr = result.reshape((10, 7), order='F')
result_arr

array([[1, 1, 0, 1, 1, 1, 1],
       [0, 1, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 1, 0, 1],
       [1, 1, 0, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 0, 0],
       [0, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

### Question 3(b) - 5 marks

Write a fuction named ``get_result_greater_than`` that returns the list of names, and their corresponding total results based on a filter.<br>
The function should accept at least ONE argument, which is the no. of courses. You should return the results filtered based on the no. of courses that he or she passes.

Example: Get the names and their total results for those who passed more than 4 courses. The result will give below output:

<br>
<img src="F3.png", style="width:1000px";>

In [ ]:
# WRITE YOUR CODE HERE
def get_result_greater_than(no_of_courses):
    global result_arr
    global name_list

    student_pass_course = []
    student_name = []
    no_course_passes = result_arr.sum(axis=1)
    for passes, name in zip(list(no_course_passes), list(name_list)):
        if passes > no_of_courses:
            student_pass_course.append(passes)
            student_name.append(name)
    return (np.array(student_pass_course), np.array(student_name))

In [ ]:
# Test Code 1

print(get_result_greater_than(6))

(array([7]), array(['S10'], dtype='<U3'))


In [ ]:
# Test Code 2

print(get_result_greater_than(4))

(array([6, 5, 5, 5, 6, 5, 7]), array(['S1', 'S5', 'S6', 'S7', 'S8', 'S9', 'S10'], dtype='<U3'))


### Question 3(c) - 5 marks

Write a fuction named ``get_result_by_name`` that returns the 7-course results for a specific student.<br>
The function should accept at least ONE argument, which is the name of the person. You should return the results filtered based on the name. If the name is not exist, 'The name is not found' should be displayed.

Example: Get the 7-course results for "S7". The result will be [0 1 0 1 1 0 1]

In [ ]:
# WRITE YOUR CODE HERE
def get_result_by_name(student_name):
    global result_arr
    global name_list

    if student_name not in name_list:
        return "The name is not found"
    index = int(student_name[1:]) - 1
    return result_arr[index]


In [ ]:
# Test Code 1

print(get_result_by_name("S7"))

[0 1 1 0 1 1 1]


In [ ]:
# Test Code 2

print(get_result_by_name("S15"))

The name is not found


### Question 3(d) - 4 marks

Calculate the percentage of pass for each course.

In [ ]:
# WRITE YOUR CODE HERE
percent_pass_course = (result_arr.sum(axis=0)/len(result_arr)) * 100
percent_pass_course

array([ 60., 100.,  70.,  60., 100.,  50.,  70.])

### Question 3(d) - 3 marks

Calculate the percentage of failure for each students.


In [ ]:
# WRITE YOUR CODE HERE
percent_fail_student = (1 - result_arr.sum(axis=1)/len(course_list)) * 100
percent_fail_student

array([14.28571429, 42.85714286, 42.85714286, 42.85714286, 28.57142857,
       28.57142857, 28.57142857, 14.28571429, 28.57142857,  0.        ])

# END OF MID TERM TEST